### ISSUE TITLE
Example says NUL, not NULL

### ISSUE THREAD

**Issue by BentTranberg** [veepee-oss/Vp.FSharp.Sql.SqlServer#4]
I assume it's a typo in the doc page. If it's intended, it should be documented with a comment in the source to avoid confusion.

`SqlServerCommand.text "SELECT NUL;"`

It's in the example for `executeScalarOrNone<'Scalar>`, but maybe search the page(s) anyway.

**Comment by natalie-o-perret** [comment]
@BentTranberg hey, did also miss that one out.
Catching up... 6 months later, the number of issues soaring these days.

Note: also thanks!

**Comment by natalie-o-perret** [comment]
Fixed

Thanks again!
